# Generated by Django 4.2 on 2023-10-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_usuarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
