# Generated by Django 4.2 on 2023-10-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertunta', models.TextField(max_length=500)),
                ('resposta', models.TextField(max_length=500)),
            ],
        ),
    ]
