# Generated by Django 4.2 on 2023-10-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_avaliacaopergunta_rename_perguntas_pergunta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='perguntasBD',
            fields=[
                ('id_pergunta', models.AutoField(primary_key=True, serialize=False)),
                ('materia', models.TextField(max_length=255)),
                ('titulo', models.TextField(max_length=255)),
                ('pergunta', models.TextField(max_length=1500)),
                ('resposta', models.TextField(max_length=1500)),
            ],
        ),
    ]
