# Generated by Django 4.2.5 on 2023-10-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_perguntasbd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(choices=[('3 perguntas', '3'), ('5 perguntas', '5'), ('7 perguntas', '7'), ('9 perguntas', '9')], max_length=15)),
            ],
        ),
    ]
