# Generated by Django 4.2.5 on 2023-10-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_perguntasbd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metas',
            old_name='meta',
            new_name='domingo',
        ),
        migrations.AddField(
            model_name='metas',
            name='quarta',
            field=models.CharField(choices=[('3 perguntas', '3'), ('5 perguntas', '5'), ('7 perguntas', '7'), ('9 perguntas', '9')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metas',
            name='quinta',
            field=models.CharField(choices=[('3 perguntas', '3'), ('5 perguntas', '5'), ('7 perguntas', '7'), ('9 perguntas', '9')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metas',
            name='sabado',
            field=models.CharField(choices=[('3 perguntas', '3'), ('5 perguntas', '5'), ('7 perguntas', '7'), ('9 perguntas', '9')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metas',
            name='segunda',
            field=models.CharField(choices=[('3 perguntas', '3'), ('5 perguntas', '5'), ('7 perguntas', '7'), ('9 perguntas', '9')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metas',
            name='sexta',
            field=models.CharField(choices=[('3 perguntas', '3'), ('5 perguntas', '5'), ('7 perguntas', '7'), ('9 perguntas', '9')], default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metas',
            name='terca',
            field=models.CharField(choices=[('3 perguntas', '3'), ('5 perguntas', '5'), ('7 perguntas', '7'), ('9 perguntas', '9')], default=0, max_length=15),
            preserve_default=False,
        ),
    ]
