# Generated by Django 4.2.5 on 2023-10-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_meta_delete_metas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('posicao', models.IntegerField()),
                ('nome', models.TextField(max_length=255)),
                ('sobrenome', models.TextField(max_length=255)),
                ('pontos', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
