# Generated by Django 4.2 on 2023-10-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_ranking_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_nova', models.TextField(max_length=255)),
            ],
        ),
    ]
